### ISSUE TITLE
The example codes do not work

### ISSUE THREAD

**Issue by JiacongSun** [zqj2333/PANDA#1]
Hi,

I am interested in your work and would like to explore the flow within your framework. However, it appears that certain files are missing, and the provided examples are not functioning properly.

To be more precise, 

1. the file `panda_feature.npy` is referenced in `./power_model/PANDA.py`, but it appears to be absent from the repository. 
2. I couldn't find files named `1_run_gem5.py` and `2_run_mcpat.py` within the `./arch_sim_flow` directory.

Is it possible that these files were inadvertently omitted from the repository?

Thank you for your attention to this matter.

Best regards,
Jiacong

**Comment by zqj2333** [comment]
Hi Jiacong,

Thanks for your interest about our research. 

Yes, we plan to open-source an example dataset for PANDA, it will be ready in a few weeks. 

You can also easily generate the dataset. The architectural simulator output can be obtained by running the gem5 and McPAT, you can use a parser to transform the gem5 output to the input of McPAT, which can be easily found on the github. The ground truth can be obtained by firstly generating the RTL code and performing RTL simulation with chipyard, then performing power simulation.

Best regards,
Qijun

**Comment by JiacongSun** [comment]
Hi Qijun,

Thanks for your response!

I'm currently not familiar with gem5, McPAT, and chipyard, so generating the dataset may require some effort on my part.

It's great to know you'll be providing examples within your framework! This will be helpful for someone like me. I'll await your update on this matter.

Best regards,
Jiacong
